name: library_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  awesome_notifications: ^0.7.4+1
  cupertino_icons: ^1.0.2
  dio: ^5.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_file_downloader: ^1.1.2
  flutter_svg: ^2.0.6
  go_router: ^8.0.1
  readmore: ^2.2.0
  share_plus: ^7.0.2
  star_rating: ^0.11.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: SansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
